name: Haskell

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GHC and Cabal
        uses: haskell/actions/setup@v2
        with:
          # Version numbers as in the top-level README.md file too
          cabal-version: 3.12.1.0
          ghc-version: 9.10.1

      - name: Install dependencies
        run: cabal update

      - name: Build the project
        run: cabal build all

      - name: Run Haskell tests
        run: cabal test all

      - name: Run integration tests
        run: |
          cabal run min-mega-exe -- --input-map map.txt
